module.exports = {
  apps: [
    {
      name: "choromanski-trading-backend",
      script: "src/index.js",
      cwd: __dirname,
      env_file: ".env",
      env: {
        AI_AGENT_SWEEP_CONCURRENCY: 3,
        DATA_DIR: "./data",
        HOST: "127.0.0.1",
        NODE_ENV: "production",
        PM2_WATCH: "false",
        PORT: 8787,
        SZTAB_AUTO_RESUME_ON_START: "false",
        SZTAB_AUTO_RECOVER_RUNNERS: "true",
        SZTAB_EXECUTION_MODE: "exchange_trigger",
        SZTAB_MARGIN_FEE_BUFFER_PCT: 0.10,
        SZTAB_MARGIN_USAGE_CAP: 0.80,
        SZTAB_MAX_TRIGGER_SLIPPAGE_PCT: 0.05,
        SZTAB_MAX_CONSECUTIVE_ERRORS: 5,
        SZTAB_MAX_TRANSIENT_ERRORS_BEFORE_PAUSE: 20,
        SZTAB_PRICE_FRESH_MS: 1200,
        SZTAB_PRICE_MAX_STALE_MS: 3000,
        SZTAB_PRICE_REST_BACKOFF_MS: 2000,
        SZTAB_PRICE_REST_BACKOFF_MAX_MS: 30000,
        SZTAB_PRICE_REST_MIN_INTERVAL_MS: 1000,
        SZTAB_PRICE_SOURCE: "bingx_mark",
        SZTAB_RUNNER_RECOVERY_COOLDOWN_MS: 10000,
        SZTAB_RUNNER_STALE_SECONDS: 120,
        SZTAB_TRIGGER_WATCH_MS: 1000,
        BINGX_PRICE_WEBSOCKET_ENABLED: "true",
        BINGX_PRICE_WS_URL: "",
      },
      autorestart: true,
      exp_backoff_restart_delay: 5000,
      kill_timeout: 8000,
      max_memory_restart: "1200M",
      min_uptime: "10s",
      restart_delay: 3000,
      watch: false,
      ignore_watch: [
        "node_modules",
        "data",
        "logs",
        "cache",
        "artifacts",
        "*.json",
        "*.tmp",
        "**/*.json",
        "**/*.tmp",
      ],
      error_file: "logs/error.log",
      out_file: "logs/out.log",
      log_file: "logs/combined.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      merge_logs: true,
      time: true,
    },
  ],
};
