module.exports = {
  apps: [
    {
      name: "choromanski-trading-backend",
      script: "src/index.js",
      cwd: __dirname,
      env_file: ".env",
      env: {
        AI_AGENT_SWEEP_CONCURRENCY: 3,
        NODE_ENV: "production",
        PM2_WATCH: "false",
        PORT: 8787,
      },
      autorestart: true,
      max_memory_restart: "1200M",
      min_uptime: "10s",
      restart_delay: 3000,
      watch: false,
      ignore_watch: [
        "node_modules",
        "data",
        "logs",
        "cache",
        "artifacts",
        "*.json",
        "*.tmp",
        "**/*.json",
        "**/*.tmp",
      ],
      error_file: "logs/error.log",
      out_file: "logs/out.log",
      log_file: "logs/combined.log",
      time: true,
    },
  ],
};
