module.exports = {
  apps: [
    {
      name: "choromanski-trading-backend",
      script: "src/index.js",
      cwd: __dirname,
      env_file: ".env",
      env: {
        AI_AGENT_SWEEP_CONCURRENCY: 3,
        DATA_DIR: "./data",
        HOST: "127.0.0.1",
        NODE_ENV: "production",
        PM2_WATCH: "false",
        PORT: 8787,
        SZTAB_AUTO_RESUME_ON_START: "false",
        SZTAB_MAX_CONSECUTIVE_ERRORS: 5,
        SZTAB_RUNNER_STALE_SECONDS: 120,
      },
      autorestart: true,
      exp_backoff_restart_delay: 5000,
      kill_timeout: 8000,
      max_memory_restart: "1200M",
      min_uptime: "10s",
      restart_delay: 3000,
      watch: false,
      ignore_watch: [
        "node_modules",
        "data",
        "logs",
        "cache",
        "artifacts",
        "*.json",
        "*.tmp",
        "**/*.json",
        "**/*.tmp",
      ],
      error_file: "logs/error.log",
      out_file: "logs/out.log",
      log_file: "logs/combined.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      merge_logs: true,
      time: true,
    },
  ],
};
