export const AGENT_OS_TOOL_CATALOG = [
  "runBacktest",
  "runSweep",
  "runAdaptiveSearch",
  "compareConfigs",
  "compareToBaseline",
  "validateOnConservative",
  "validateAcrossTimeframes",
  "validateAcrossPeriods",
  "getTopByMetric",
  "getClusterStability",
  "getParameterSensitivity",
  "loadCandles",
  "loadSavedBacktest",
  "loadSavedDeck",
  "loadPreviousRun",
  "getTradeList",
  "getEquityCurve",
  "getDrawdownCurve",
  "getMonthlyBreakdown",
  "getMetricDefinitions",
  "rankByPF",
  "rankByWinRate",
  "rankByNetProfit",
  "rankByDrawdown",
  "rankOverall",
  "detectOverfit",
  "detectDataMismatch",
  "explainMetricDifference",
  "findWhyManualSweepBeatAI",
  "auditSearchCoverage",
  "createMarkdownReport",
  "createWordReport",
  "createExcelWorkbook",
  "createCSV",
  "createResearchPackage",
  "exportZipManifest",
  "getCurrentWorkspaceState",
  "tracePlatformAction",
  "inspectCodePath",
  "diagnoseRuntimeIssue",
  "getLivePositionState",
  "getBacktestPanelState",
];

export function buildFileManifest(artifacts = [], context = {}) {
  return {
    artifacts: artifacts.map((artifact) => ({
      fileName: artifact.fileName,
      format: artifact.format,
      id: artifact.id,
      mime: artifact.mime,
      name: artifact.name,
      type: artifact.type,
    })),
    createdAt: new Date().toISOString(),
    context,
    toolCatalogVersion: "agent-os-v1",
  };
}
